apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/argo-rollouts
    repoURL: https://github.com/argoproj/argo-helm
  syncPolicy:
    automated:
      selfHeal: true