apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomizations/argo-workflows/envs/root
    repoURL: https://github.com/thecooldrop/argo-test-bootstrap.git