apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomizations/argocd/envs/root
    repoURL: https://github.com/thecooldrop/argo-test-bootstrap.git
  syncPolicy:
    automated:
      selfHeal: true